<a href="https://colab.research.google.com/github/baaaRaathh/Natural-Language-Processing/blob/main/Text_Similarity_Funcation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#import pack
!pip install recordlinkage

Requirement already satisfied: recordlinkage in /usr/local/lib/python3.10/dist-packages (0.16)
Requirement already satisfied: jellyfish>=1 in /usr/local/lib/python3.10/dist-packages (from recordlinkage) (1.1.0)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.10/dist-packages (from recordlinkage) (1.26.4)
Requirement already satisfied: pandas<3,>=1 in /usr/local/lib/python3.10/dist-packages (from recordlinkage) (2.2.2)
Requirement already satisfied: scipy>=1 in /usr/local/lib/python3.10/dist-packages (from recordlinkage) (1.13.1)
Requirement already satisfied: scikit-learn>=1 in /usr/local/lib/python3.10/dist-packages (from recordlinkage) (1.5.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from recordlinkage) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1->recordlinkage) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1->recordlinkage) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1->recordlinkage) (2024.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1->recordlinkage) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1->recordlinkage) (1.16.0)

In [2]:
from recordlinkage.datasets import load_febrl1
dfa = load_febrl1()
dfa.head()

             given_name     surname street_number  ... state date_of_birth soc_sec_id
rec_id                                             ...
rec-223-org         NaN      waller             6  ...    wa      19081209    6988048
rec-122-org     lachlan       berry            69  ...   qld      19990219    7364009
rec-373-org      deakin  sondergeld            48  ...   vic      19600210    2635962
rec-10-dup-0      kayla  harrington           NaN  ...   nsw      19150612    9004242
rec-227-org        luke      purdon            23  ...   vic      19831024    8099933

[5 rows x 10 columns]

#Blocking

In [3]:
from recordlinkage.index import Block

In [18]:
indexer = Block('given_name')
pair = indexer.index(dfa)
print(len(pair))

2082

#similarty Matcching and Scoring

In [13]:
dfa.head()

             given_name     surname street_number  ... state date_of_birth soc_sec_id
rec_id                                             ...
rec-223-org         NaN      waller             6  ...    wa      19081209    6988048
rec-122-org     lachlan       berry            69  ...   qld      19990219    7364009
rec-373-org      deakin  sondergeld            48  ...   vic      19600210    2635962
rec-10-dup-0      kayla  harrington           NaN  ...   nsw      19150612    9004242
rec-227-org        luke      purdon            23  ...   vic      19831024    8099933

[5 rows x 10 columns]

In [19]:
import recordlinkage
com = recordlinkage.Compare()

In [20]:
com.string('given_name','given_name',method='jarowinkler',label='given_name')
com.string('surname','surname',method='jarowinkler',label='surname')
com.exact('date_of_birth','date_of_birth',label='date_of_birth')
com.exact('state','state',label='state')
com.string('address_1','address_1',method='jarowinkler',label='address_1')
fe = com.compute(pair,dfa)
fe.sample(5)

                             given_name   surname  date_of_birth  state  address_1
rec_id_1      rec_id_2
rec-142-dup-0 rec-348-dup-0         1.0  0.511905              0      0   0.552778
rec-79-dup-0  rec-143-org           1.0  0.414286              0      1   0.501068
rec-124-org   rec-124-dup-0         1.0  0.893333              1      1   1.000000
rec-14-org    rec-14-dup-0          1.0  1.000000              1      1   1.000000
rec-50-org    rec-161-org           1.0  0.000000              0      0   0.611111

#predict the match using ECM Classifier

In [25]:
fes = fe[['given_name','surname','date_of_birth','state','address_1']]
ecm = recordlinkage.ECMClassifier()
re = ecm.learn((fes).astype(int),return_type='series')
re

<ipython-input-25-b44ed12b75e6>:3: UserWarning: learn is deprecated, ECMClassifier.fit_predict instead
  re = ecm.learn((fes).astype(int),return_type='series')

rec_id_1       rec_id_2
rec-251-org    rec-251-dup-0    1
rec-284-dup-0  rec-67-org       0
rec-335-dup-0  rec-335-org      1
rec-23-dup-0   rec-23-org       1
rec-32-dup-0   rec-70-org       0
                               ..
rec-469-dup-0  rec-183-org      0
               rec-360-dup-0    0
               rec-248-dup-0    0
rec-350-dup-0  rec-350-org      1
               rec-242-org      0
Name: classification, Length: 2082, dtype: int64